services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=SPS
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/SPS
      - FLASK_ENV=development
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "5001:5001"
    depends_on:
      - mongodb # Ensure MongoDB starts first
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  mongo_data:
