version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: flask_backend
    restart: always
    expose:
      - "5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: "no"
    restart: always
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: