import React from "react";

import styles from "./BrowsePage.module.css";

import ProductCard from "../../Components/ProductCard/ProductCards";

const BrowsePage: React.FC = () => {
    return (
        <div className = {styles.container}>
            <div className = {styles.productsContainer}>
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
                <ProductCard onClick = {() => {}} keywords = {["rock", "metallica", "ride the fulger"]} name = "tricou rock cool" description = "something to say about the cool rock t-shirt and some more text for testing" price = {99.99} imageUrl="https://i.ibb.co/Vvbzzjs/pngwing-com.png" category = "t-shirt" matchPercentage={93.5} customizations = {{backgroundColor: "var(--background-secondary)", foregroundColor: "var(--text-primary)", accentColor: "var(--background-accent)", shadow: "var(--shadow)", backgroundColorTags: "var(--background-tertiary)"}} />
            </div>
            
        </div>
    );
};

export default BrowsePage;